### PR TITLE
do not merge

### PR DESCRIPTION
**Pull request by SpamapS**

### CODE REVIEW

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/check_github/BonnyCI/bonnyci.org/25/1487181548.38/bonnyci-run-check : POST_FAILURE in 12s

**Comment by SpamapS** [comment]
recheck

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/check_github/BonnyCI/bonnyci.org/25/1487184978.08/bonnyci-run-check : POST_FAILURE in 12s

**Comment by SpamapS** [comment]
recheck

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/check_github/BonnyCI/bonnyci.org/25/1487187315.23/bonnyci-run-check : POST_FAILURE in 12s

**Pull request closed without merging**
