### PR TITLE
Document rotating the cideploy key

### PR DESCRIPTION
**Pull request by SpamapS**
This relies on the admin-user role deploying keys from secrets.

This is the last step in completing BonnyCI/hoist#189

Signed-off-by: Clint Byrum <clint@fewbar.com>

### CODE REVIEW

**Comment by ConsoleCatzirl** [comment]
:+1: Looks good

**Review by ConsoleCatzirl — APPROVED** [review]

**Review by mlangbehn — APPROVED** [review]
Looks good to me.

**Comment by SpamapS** [comment]
recheck_gate

**Comment by SpamapS** [comment]
gate-recheck

**Comment by mlangbehn** [comment]
gate-recheck

**Comment by mlangbehn** [comment]
recheck

**Pull request merged**
