### PR TITLE
Add research description to bonnyci.org site

### PR DESCRIPTION
**Pull request by missaugustina**
Closes Issue #44

Signed-off-by: Augustina Ragwitz <augustina.ragwitz@ibm.com>

### CODE REVIEW

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/check_github/BonnyCI/bonnyci.org/45/1489529133.83/bonnyci-run-check : FAILURE in 2m 15s

**Comment by anne-bonny** [comment]
Build failed.

- http://logs.bonnyci.com/check_github/BonnyCI/bonnyci.org/45/1489529354.86/bonnyci-run-check : FAILURE in 2m 15s

**Review by omgjlk — APPROVED** [review]
Looks good to me!

**Comment by anne-bonny** [comment]
Merge Failed.

This change or one of its cross-repo dependencies was unable to be automatically merged with the current state of its repository. Please rebase the change and upload a new patchset.

**Comment by omgjlk** [comment]
whoh that's a weird thing

**Pull request merged**
